# src/main/resources/application.yml
spring:
  profiles:
    active: dev

  web:
    resources:
      cache:
        use-etag: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

server:
  servlet:
    context-path: /api

  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentEnvironmentOnly}
  accessTokenExpirationMs: 3600000  # 1 hour
  refreshTokenExpirationMs: 604800000  # 7 days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /api/v3/api-docs/swagger-config
    urls:
      - url: /api/v3/api-docs
        name: API Documentation
