# src/main/resources/application-prod.yml
spring:
  datasource:
    url: jdbc:mysql://blog-ducogus12-3b56.k.aivencloud.com:17417/defaultdb?ssl-mode=REQUIRED
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  servlet:
      max-file-size: 60MB
      max-request-size: 60MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://blog-server-645l.onrender.com/api/oauth2/callback/google
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://blog-server-645l.onrender.com/api/oauth2/callback/github
            scope:
              - user:email
              - read:user
              -
  app:
    oauth2:
      redirect-uri: https://1000hyehyang.vercel.app/

cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket: blog
    endpoint: https://740ddd7540732b28b20cb6d95015a2be.r2.cloudflarestorage.com
    public-url: https://pub-7bc94e13b36142b98e97c1e4d5839a10.r2.dev
    region: auto

logging:
  level:
    root: warn