# src/main/resources/application.yml
spring:
  profiles:
    active: dev

  web:
    resources:
      cache:
        use-etag: false

server:
  servlet:
    context-path: /api

  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentEnvironmentOnly}
  accessTokenExpirationMs: 3600000  # 1 hour
  refreshTokenExpirationMs: 604800000  # 7 days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /api/v3/api-docs/swagger-config
    urls:
      - url: /api/v3/api-docs
        name: API Documentation
