# src/main/resources/application.yml
spring:
  web:
    resources:
      cache:
        use-etag: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  servlet:
    context-path: /api

  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentEnvironmentOnly}
  accessTokenExpirationMs: 3600000  # 1 hour
  refreshTokenExpirationMs: 604800000  # 7 days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /api/v3/api-docs/swagger-config
    urls:
      - url: /api/v3/api-docs
        name: API Documentation
